### PR TITLE
Use generic-flonum Racket package for float evaluation

### PR DESCRIPTION
**Pull request by bksaiki**
This PR switches the reference interpreter and testing infrastructure to use the new [generic-flonum](http://docs.racket-lang.org/generic-flonum.html) MPFR interface rather than the standard [math/bigfloat](http://docs.racket-lang.org/math/bigfloat.html) interface. Unlike Racket's bigfloat library, generic-flonum correctly emulates subnormal numbers and restricts the exponent range. Tests should no longer fail when the random sampler produces inputs that result in a subnormal output (see #91).

Other minor changes include:
 - enabled tests containing 'fmod', 'remainder' (not provided by bigfloat)
 - enabled tests containing 'round' (provided by bigfloat, known to be incorrect (has this changed?))
 - enabled tests containing 'isnormal' (not provided by MPFR)
 - rounding mode: away (not supported by bigfloat)
 - float evaluator (supports any float with the format `(float es nbits)`)
 - better integer evaluator
 - FPCore 2.0 tensor examples for testing
 - Tests for `binary80` (bugs found)

This first three in the list above (hopefully) resolves all of #53 since the reference interpreter was not correct to begin with, but this should be investigated further.

### CODE REVIEW

**Comment by pavpanchekha** [comment]
@bksaiki what's with the test failure here? Looks like something should have been parsed and wasn't?

**Comment by bksaiki** [comment]
It's just a bad conversion between floats in the tester (generic-flonum) and floats in the compiler (Racket flonums). Hopefully, it's all good now.

**Comment by pavpanchekha** [comment]
I think you have some empty filter commands in the makefile, but in general, this is a big win.

**Comment by bksaiki** [comment]
Ah, thanks. I'll fix and then merge.

**Pull request merged**
