### PR TITLE
Support let expressions in tex compiler

### PR DESCRIPTION
**Pull request by bksaiki**
This PR adds support for `let` and `let*` within the tex compiler.

### CODE REVIEW

**Review by pavpanchekha — CHANGES_REQUESTED** [review]
I'm not sure I understand how this `array` system works. Or—I think I understand it, but I don't understand why we need something this complex, instead of just a single array and the global depth variable.

Unrelated to that, `let` and `let*` with multiple variables should be distinguishable! I propose that for `let` we should put multiple assignments on one line, as in Python:

    (let ([a b] [b a]) b)
    -->
    a, b := b, a

**Comment by bksaiki** [comment]
The TeX compiler is split into two separate paths. The first is used when the expression is a single-line, i.e. no `if` and `let` expressions. The second is used when the expression is multi-lined. The output will be wrong only if there is an `if` subexpression (`if` is not at the top or directly below an `if` or `let` statement at the top), or if an `if` or `let` statement is inside the value of a `let` binding. These edge cases are quite difficult to deal with, and they really should be rewritten to be better programs.

**Comment by pavpanchekha** [comment]
This looks a lot simpler. I think there's now some dead code in the file. And a quick question—do we need the `texify` function inside `stmt->tex`? Can we just recursively call `stmt->tex`? I think the that `texify` function meant we didn't have to re-pass the `color-loc` argument but at this point that's kind of a lost cause---we still need it when calling `expr->tex` and there's a lot of arguments however you slice it.

**Comment by bksaiki** [comment]
Attempt 3: tex compiler uses two different, mutually-recursive procedures: `expr->tex` and `stmt->tex`. The first handles all single-line expressions and the second handles `if` and `let` expressions. The output of `stmt->tex` is immediately wrapped in an `array` environment. This solves the indentation issue and is much cleaner. Nested `let` expressions still render weird, but these can be written off as bad programs.

**Comment by bksaiki** [comment]
I suppose we could do without `texify` in `stmt->tex` since it's only called twice. I should still experiment with `\mbox` as well.

**Comment by pavpanchekha** [comment]
Nice, ok. Yeah, I think we can drop the `texify`. Honestly it is nice to see the TeX compiler simplified like this. (Color tracking is the remaining nasty thing!) It's also a lot clearer now how we could add, for example, `while` loops to it.

**Comment by pavpanchekha** [comment]
Nice! I think once you've got the over `texify` gone we can go ahead and merge this.

**Review by pavpanchekha — APPROVED** [review]

**Pull request merged**
