### PR TITLE
Update and reorganize FPBench tools

### PR DESCRIPTION
**Pull request by billzorn**
This is the main pull request for the FPBench tool release.

Still WIP.

It occurs to me that maybe it should be moved to the main repo rather than my fork.

### CODE REVIEW

**Comment by pavpanchekha** [comment]
Looks good so far, you do have some debugging code left over but the PR suggests that it's WIP.

**Comment by pavpanchekha** [comment]
I noticed that you have the Gappa flags but not Gappa support (nor FPTaylor). Any reason those are harder, or is it just an oversight?

**Comment by billzorn** [comment]
Gappa and FPTaylor have more flags to convert into arguments, and I need to figure out which ones to figure out and pass from export.rkt, and which ones should be handled by performing other passes first (like unrolling).

**Comment by pavpanchekha** [comment]
I just took a look; here's what I think:

+ The `stdout`, `auto-file-names`, and `out-path` parameters are weird and we'd ideally talk to an FPTaylor or Gappa user before doing anything about them. They could in principle apply to any compiler, but I also suspect that it would not be the biggest regression if we dropped them.
+ The `rel-error` flag we should keep
+ `precision` and `var-precision` we should drop. Programmatically changing precisions is better suited to the desugaring tool.
+ `split-or`, `split`, and `unroll` should move to the desugaring tool.
+ `subexprs` I have no strong feeling on. I'd be inclined to keep it a compiler flag, or drop it if it's not that important.

**Comment by billzorn** [comment]
Closed in favor of #43

**Pull request closed without merging**
