### PR TITLE
Update to Racket 8.0

### PR DESCRIPTION
**Pull request by bksaiki**
This PR supports Racket 8.0 by borrowing Herbie's single-flonum compatability library. The CI runner has been bumped to "ubuntu-latest" since support for 16.04 is ending. Also added Java and OCaml actions to CI for a cleaner and faster setup.

### CODE REVIEW

**Comment by pavpanchekha** [comment]
This is good stuff. A few questions:

- You removed the caching action—is that right? Why?
- There are probably other actions we should use, like to set up SBT. It's like Sollya does not have an action, but perhaps we should factor that out?
- What is the single-precision support in the FPBench tools about? Perhaps the right move is actually to rip it out? (If it's about the reference interpreter, I see no real reason the reference interpreter should support single-precision if it also supports double.)

**Comment by bksaiki** [comment]
I removed caching because its caused more problems than helped. It's extremely messy when changing CI. Making every install an action would probably clean things up even more. Single precision is needed to force rounding when testing single-precision.

**Comment by pavpanchekha** [comment]
Ok, I'm fine with that reason for removing rounding.

For actions per-project, that seems like 1) a nice thing for FPBench to maintain, and 2) check out my `setup-z3` action for a simple template, unfortunately the docs are not quite as good as you'd like here.

What do you mean by "forcing rounding when testing single-precision"? Isn't that just `flsingle`? And what are we comparing against?

**Comment by bksaiki** [comment]
Issue resolved. Did some testing and I found the float32 library is unnecessary since the reference interpreter and the sampler will produce valid single-precision values.

**Pull request merged**
