### PR TITLE
Add benchmarks from #82

### PR DESCRIPTION
**Pull request by pavpanchekha**
I only took those benchmarks that seemed non-trivial (there are a few that just evaluate Taylor expansions of a few common functions) and I deduplicated heavily.

### CODE REVIEW

**Comment by bksaiki** [comment]
I need to get all the languages to skip tensor tests.

**Comment by pavpanchekha** [comment]
Yes

**Comment by bksaiki** [comment]
Should merging this close #82 ?

**Comment by pavpanchekha** [comment]
What’s with the failed test? If it works let’s merge.

**Pull request merged**
